#include <iostream>
#include <vector>
#include <list>
#include <functional>
using namespace std;

template <typename K, typename V> //use of template gives us the flexibility to work with any datatype without further declaring it, hence we can make maps with types <string, int> or <char, string>, etc.
class HashMap{
    typedef pair<K, V> Pair;
    typedef list<Pair> Bucket;

    vector<Bucket> buckets; // The Core data Structure for maps is a vector of linked lists that holds nodes of pairs(key, value)

    int count = 0; // maintains our size of the map(the number of total pairs present)

    float load_factor = 1.0f;
    //The Load Factor is about the threshold limit of holding the nodes in the list {load_factor = number of elements inserted/ number of buckets present}, the higher number means we have more elements in a bucket that holding capacity, we makes it to look up for O(n) time complexity

    //After inserting each insetion, we look up for the load_factor to see the need of rehashing(increasing the vector size of the buckets ensuring to go back to O(1) complexity)

    int bucket_index(const K& key) const {
        return hash<K>{}(key) % buckets.size();

        //We hash the key no matter the datatype to get a number and we get it to the modulo of our buckets.size() to get a index to add the pair in the list at that index

        /*The hash function here is a built-in function from the functional library, it follows:
            -hash<datatype of the key>
            - {} -> creates an object for it
            - (key) -> the actual thing to be hashed
        */
    }

    //The rehash Function is used when we cross the threshold load_factor making the size of the vector<Bucket> more(2 times incase of here)
    void rehash(){
        vector<Bucket> old = move(buckets); //move ensures the current vector doesn't get copied but rather be transferred from one memory to another(old vector here)
        buckets.assign(old.size() * 2, Bucket{});
        //We now change our original buckets vector with twice the size with a empty list, we can stored our already existing values with new indexes generated by our insert function
        count = 0;
        for (auto& b : old){
            for (auto& [k, v] : b){
                insert(k, v);
            }    
        }
    }

    
};