#include <iostream>
#include <vector>
#include <list>
#include <functional>
using namespace std;

template <typename K, typename V> //use of template gives us the flexibility to work with any datatype without further declaring it, hence we can make maps with types <string, int> or <char, string>, etc.
class HashMap{
    typedef pair<K, V> Pair;
    typedef list<Pair> Bucket;

    vector<Bucket> buckets; // The Core data Structure for maps is a vector of linked lists that holds nodes of pairs(key, value)

    int count = 0; // maintains our size of the map(the number of total pairs present)

    float load_factor = 1.0f;
    //The Load Factor is about the threshold limit of holding the nodes in the list {load_factor = number of elements inserted/ number of buckets present}, the higher number means we have more elements in a bucket that holding capacity, we makes it to look up for O(n) time complexity

    //After inserting each insetion, we look up for the load_factor to see the need of rehashing(increasing the vector size of the buckets ensuring to go back to O(1) complexity)

    int bucket_index(const K& key) const {
        return hash<K>{}(key) % buckets.size();

        //We hash the key no matter the datatype to get a number and we get it to the modulo of our buckets.size() to get a index to add the pair in the list at that index

        /*The hash function here is a built-in function from the functional library, it follows:
            -hash<datatype of the key>
            - {} -> creates an object for it
            - (key) -> the actual thing to be hashed
        */
    }

    //The rehash Function is used when we cross the threshold load_factor making the size of the vector<Bucket> more(2 times incase of here)
    void rehash(){
        vector<Bucket> old = move(buckets); //move ensures the current vector doesn't get copied but rather be transferred from one memory to another(old vector here)
        buckets.assign(old.size() * 2, Bucket{});
        //We now change our original buckets vector with twice the size with a empty list, we can stored our already existing values with new indexes generated by our insert function
        count = 0;
        for (auto& b : old){
            for (auto& [k, v] : b){
                insert(k, v);
            }    
        }
    }
    
public:
    explicit HashMap(int initial_buckets = 16)
        : buckets(initial_buckets) {}
        //Initializing the vector with the help of initializer list
        //Initializer List is used for giving values faster than regular assignment which gives value after object creation and but in Initializer list, value is giving during the creation of the object

    
    //Inserting the key-value pair in the bucket
    void insert(const K& key, const V& val){
        if((float)(count+1) / buckets.size() > load_factor){
            rehash();
            /*check for the threshold, if it is greater than 1 on adding the new pair, so we rehash the table to lower the load_factor */
        }

        auto& bucket = buckets[bucket_index(key)];
        //Get the index by hashing the key, and then traversing the list at that index if the key exists already the value is updated
        for(auto& [k, v] : bucket){
            if(k == key){
                v = val;
                return;
            }
        }
        //Runs when a brand new key is to be inserted, as it existed it would have been returned earlier
        bucket.emplace_front(key, val)
        //we didnt use push front because,
        //push_front make first, then put
        //emplace_front make directly there
        ++count;
    }
    
    //Function to get the value from its key
    //Sending the reference of the value instead of a copy which avoids using extra memory
    V& get(const K& key){
        auto& bucket = buckets[bucket_index(key)];
        for(auto& [k, v] : bucket){
            if(k == key) return v;
        }
        //We raise an exception if we don't find any value to the corresponding key
        //throws -> immediately stops the execution as an error has occured
        //out_of_range is a type of exception that shows error when values are out of bound, or invalid index like here
        throw out_of_range("key not found");
    }

    //Function to delete a key-value pair
    bool erase(const K& key){
        //Getting the linked list
        auto& bucket = buckets[bucket_index(key)];
        //using an iterator it to traverse the linked list
        for(auto it = bucket.begin(); it != bucket.end(); it++){
            //check for the key
            if(it->first == key){
                bucket.erase(it);
                //used the erase function of <list> to erase the [K, V] pair
                count--;
                //decreasing the size

                return true; //for successful deletion
            }
        }

        return false; //When key is not deleted
    }

    //check if key is present or not
    //Same old traversal on list after finding the hashed index
    bool contains(const K& key){
        auto& bucket = buckets[bucket_index(key)];
        for(auto& [k, v] : bucket){
            if(k == key) return true;
        }

        return false;
    }
};